version: "3.12"

services:
  postgres:
    image: postgres:15
    container_name: incident-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5434:5432"]           # ← different host port to avoid conflicts
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata_incident:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: incident-airflow-web
    depends_on: [postgres]
    environment:
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.2 psycopg2-binary==2.9.9"
    ports: ["8090:8080"]           # ← project UI on http://localhost:8090
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/requirements.txt:/requirements.txt
      - ./data:/opt/airflow/data
    command: bash -c "pip install -r /requirements.txt && airflow db init && airflow users create --username admin --password admin --firstname A --lastname I --role Admin --email admin@example.com || true && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: incident-airflow-scheduler
    depends_on: [airflow-webserver]
    environment:
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.2 psycopg2-binary==2.9.9"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/requirements.txt:/requirements.txt
      - ./data:/opt/airflow/data
    command: bash -c "pip install -r /requirements.txt && airflow scheduler"

volumes:
  pgdata_incident:
