{{ config(materialized='view') }}

select
  number,
  incident_state,
  cast(active as boolean)                           as active,
  cast(reassignment_count as integer)               as reassignment_count,
  cast(reopen_count as integer)                     as reopen_count,
  cast(sys_mod_count as integer)                    as sys_mod_count,
  cast(made_sla as boolean)                         as made_sla,
  caller_id,
  opened_by,
  opened_at::timestamp                              as opened_at,
  sys_created_by,
  sys_created_at::timestamp                         as sys_created_at,
  sys_updated_by,
  sys_updated_at::timestamp                         as sys_updated_at,
  contact_type,
  location,
  category,
  subcategory,
  u_symptom,
  nullif(cmdb_ci,'?')                               as cmdb_ci,
  cast(impact as integer)                           as impact,
  cast(urgency as integer)                          as urgency,
  cast(priority as integer)                         as priority,
  assignment_group,
  assigned_to,
  cast(knowledge as boolean)                        as knowledge,
  cast(u_priority_confirmation as boolean)          as u_priority_confirmation,
  notify,
  nullif(problem_id,'?')                            as problem_id,
  nullif(rfc,'?')                                   as rfc,
  vendor,
  caused_by,
  close_code,
  resolved_by,
  resolved_at::timestamp                            as resolved_at,
  closed_at::timestamp                              as closed_at
from raw.uci_incident_events
