CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.uci_incident_events (
  number TEXT,
  incident_state TEXT,
  active BOOLEAN,
  reassignment_count INT,
  reopen_count INT,
  sys_mod_count INT,
  made_sla BOOLEAN,
  caller_id TEXT,
  opened_by TEXT,
  opened_at TIMESTAMP,
  sys_created_by TEXT,
  sys_created_at TIMESTAMP,
  sys_updated_by TEXT,
  sys_updated_at TIMESTAMP,
  contact_type TEXT,
  location TEXT,
  category TEXT,
  subcategory TEXT,
  u_symptom TEXT,
  cmdb_ci TEXT,
  impact INT,
  urgency INT,
  priority INT,
  assignment_group TEXT,
  assigned_to TEXT,
  knowledge BOOLEAN,
  u_priority_confirmation BOOLEAN,
  notify TEXT,
  problem_id TEXT,
  rfc TEXT,
  vendor TEXT,
  caused_by TEXT,
  close_code TEXT,
  resolved_by TEXT,
  resolved_at TIMESTAMP,
  closed_at TIMESTAMP,
  _ingested_at TIMESTAMP DEFAULT NOW()
);
